"""initial_schema

Revision ID: 92e46cb423de
Revises: 
Create Date: 2026-01-14 17:42:52.198058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '92e46cb423de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_active_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('resource_limits', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_user_status', 'sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_session_id'), 'projects', ['session_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_heartbeat_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('checkpoint_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_runs_agent_status', 'workflow_runs', ['agent', 'status'], unique=False)
    op.create_index('idx_workflow_runs_session_status', 'workflow_runs', ['session_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_agent'), 'workflow_runs', ['agent'], unique=False)
    op.create_index(op.f('ix_workflow_runs_mode'), 'workflow_runs', ['mode'], unique=False)
    op.create_index(op.f('ix_workflow_runs_session_id'), 'workflow_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_table('dag_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dag_nodes_run_order', 'dag_nodes', ['run_id', 'order_index'], unique=False)
    op.create_index('idx_dag_nodes_type_status', 'dag_nodes', ['node_type', 'status'], unique=False)
    op.create_index(op.f('ix_dag_nodes_node_type'), 'dag_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_dag_nodes_run_id'), 'dag_nodes', ['run_id'], unique=False)
    op.create_index(op.f('ix_dag_nodes_session_id'), 'dag_nodes', ['session_id'], unique=False)
    op.create_index(op.f('ix_dag_nodes_status'), 'dag_nodes', ['status'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('inputs', sqlite.JSON(), nullable=True),
    sa.Column('outputs', sqlite.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100', name='check_progress_range'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_steps_run_number', 'workflow_steps', ['run_id', 'step_number'], unique=False)
    op.create_index('idx_workflow_steps_session_status', 'workflow_steps', ['session_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_steps_run_id'), 'workflow_steps', ['run_id'], unique=False)
    op.create_index(op.f('ix_workflow_steps_session_id'), 'workflow_steps', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflow_steps_status'), 'workflow_steps', ['status'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('context_snapshot', sqlite.JSON(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approval_requests_run_requested', 'approval_requests', ['run_id', 'requested_at'], unique=False)
    op.create_index('idx_approval_requests_status', 'approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_approval_requests_run_id'), 'approval_requests', ['run_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_approval_requests_step_id'), 'approval_requests', ['step_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_run_id', sa.String(length=36), nullable=False),
    sa.Column('parent_step_id', sa.String(length=36), nullable=False),
    sa.Column('child_run_id', sa.String(length=36), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['child_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_branches_child_run', 'branches', ['child_run_id'], unique=False)
    op.create_index('idx_branches_parent_run', 'branches', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_branches_child_run_id'), 'branches', ['child_run_id'], unique=False)
    op.create_index(op.f('ix_branches_parent_run_id'), 'branches', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_branches_parent_step_id'), 'branches', ['parent_step_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('checkpoint_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('context_snapshot', sqlite.JSON(), nullable=True),
    sa.Column('pickle_file_path', sa.String(length=500), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checkpoints_run_created', 'checkpoints', ['run_id', 'created_at'], unique=False)
    op.create_index('idx_checkpoints_type', 'checkpoints', ['checkpoint_type'], unique=False)
    op.create_index(op.f('ix_checkpoints_checkpoint_type'), 'checkpoints', ['checkpoint_type'], unique=False)
    op.create_index(op.f('ix_checkpoints_run_id'), 'checkpoints', ['run_id'], unique=False)
    op.create_index(op.f('ix_checkpoints_step_id'), 'checkpoints', ['step_id'], unique=False)
    op.create_table('cost_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_records_model', 'cost_records', ['model'], unique=False)
    op.create_index('idx_cost_records_run_timestamp', 'cost_records', ['run_id', 'timestamp'], unique=False)
    op.create_index('idx_cost_records_session_timestamp', 'cost_records', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_cost_records_model'), 'cost_records', ['model'], unique=False)
    op.create_index(op.f('ix_cost_records_run_id'), 'cost_records', ['run_id'], unique=False)
    op.create_index(op.f('ix_cost_records_session_id'), 'cost_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_cost_records_step_id'), 'cost_records', ['step_id'], unique=False)
    op.create_table('dag_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_node_id', sa.String(length=36), nullable=False),
    sa.Column('to_node_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['dag_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['dag_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dag_edges_from_to', 'dag_edges', ['from_node_id', 'to_node_id'], unique=False)
    op.create_index(op.f('ix_dag_edges_from_node_id'), 'dag_edges', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_dag_edges_to_node_id'), 'dag_edges', ['to_node_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_created', 'files', ['created_at'], unique=False)
    op.create_index('idx_files_run_type', 'files', ['run_id', 'file_type'], unique=False)
    op.create_index(op.f('ix_files_file_type'), 'files', ['file_type'], unique=False)
    op.create_index(op.f('ix_files_run_id'), 'files', ['run_id'], unique=False)
    op.create_index(op.f('ix_files_step_id'), 'files', ['step_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('recipient', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_run_timestamp', 'messages', ['run_id', 'timestamp'], unique=False)
    op.create_index('idx_messages_sender_recipient', 'messages', ['sender', 'recipient'], unique=False)
    op.create_index(op.f('ix_messages_recipient'), 'messages', ['recipient'], unique=False)
    op.create_index(op.f('ix_messages_run_id'), 'messages', ['run_id'], unique=False)
    op.create_index(op.f('ix_messages_sender'), 'messages', ['sender'], unique=False)
    op.create_index(op.f('ix_messages_step_id'), 'messages', ['step_id'], unique=False)
    op.create_table('workflow_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(), nullable=False),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_metrics_run_name', 'workflow_metrics', ['run_id', 'metric_name'], unique=False)
    op.create_index('idx_workflow_metrics_timestamp', 'workflow_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_workflow_metrics_metric_name'), 'workflow_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_workflow_metrics_run_id'), 'workflow_metrics', ['run_id'], unique=False)
    op.create_index(op.f('ix_workflow_metrics_step_id'), 'workflow_metrics', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_metrics_step_id'), table_name='workflow_metrics')
    op.drop_index(op.f('ix_workflow_metrics_run_id'), table_name='workflow_metrics')
    op.drop_index(op.f('ix_workflow_metrics_metric_name'), table_name='workflow_metrics')
    op.drop_index('idx_workflow_metrics_timestamp', table_name='workflow_metrics')
    op.drop_index('idx_workflow_metrics_run_name', table_name='workflow_metrics')
    op.drop_table('workflow_metrics')
    op.drop_index(op.f('ix_messages_step_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender'), table_name='messages')
    op.drop_index(op.f('ix_messages_run_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient'), table_name='messages')
    op.drop_index('idx_messages_sender_recipient', table_name='messages')
    op.drop_index('idx_messages_run_timestamp', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_files_step_id'), table_name='files')
    op.drop_index(op.f('ix_files_run_id'), table_name='files')
    op.drop_index(op.f('ix_files_file_type'), table_name='files')
    op.drop_index('idx_files_run_type', table_name='files')
    op.drop_index('idx_files_created', table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_dag_edges_to_node_id'), table_name='dag_edges')
    op.drop_index(op.f('ix_dag_edges_from_node_id'), table_name='dag_edges')
    op.drop_index('idx_dag_edges_from_to', table_name='dag_edges')
    op.drop_table('dag_edges')
    op.drop_index(op.f('ix_cost_records_step_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_session_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_run_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_model'), table_name='cost_records')
    op.drop_index('idx_cost_records_session_timestamp', table_name='cost_records')
    op.drop_index('idx_cost_records_run_timestamp', table_name='cost_records')
    op.drop_index('idx_cost_records_model', table_name='cost_records')
    op.drop_table('cost_records')
    op.drop_index(op.f('ix_checkpoints_step_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_run_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_checkpoint_type'), table_name='checkpoints')
    op.drop_index('idx_checkpoints_type', table_name='checkpoints')
    op.drop_index('idx_checkpoints_run_created', table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_branches_parent_step_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_parent_run_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_child_run_id'), table_name='branches')
    op.drop_index('idx_branches_parent_run', table_name='branches')
    op.drop_index('idx_branches_child_run', table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_approval_requests_step_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_run_id'), table_name='approval_requests')
    op.drop_index('idx_approval_requests_status', table_name='approval_requests')
    op.drop_index('idx_approval_requests_run_requested', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_workflow_steps_status'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_session_id'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_run_id'), table_name='workflow_steps')
    op.drop_index('idx_workflow_steps_session_status', table_name='workflow_steps')
    op.drop_index('idx_workflow_steps_run_number', table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_dag_nodes_status'), table_name='dag_nodes')
    op.drop_index(op.f('ix_dag_nodes_session_id'), table_name='dag_nodes')
    op.drop_index(op.f('ix_dag_nodes_run_id'), table_name='dag_nodes')
    op.drop_index(op.f('ix_dag_nodes_node_type'), table_name='dag_nodes')
    op.drop_index('idx_dag_nodes_type_status', table_name='dag_nodes')
    op.drop_index('idx_dag_nodes_run_order', table_name='dag_nodes')
    op.drop_table('dag_nodes')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_session_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_mode'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_agent'), table_name='workflow_runs')
    op.drop_index('idx_workflow_runs_session_status', table_name='workflow_runs')
    op.drop_index('idx_workflow_runs_agent_status', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_projects_session_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index('idx_sessions_user_status', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
